// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ColorChange
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "color_id")]
        public uint ColorId;

        public ColorChange(
            uint EntityId,
            uint ColorId
        )
        {
            this.EntityId = EntityId;
            this.ColorId = ColorId;
        }

        public ColorChange()
        {
        }
    }
}
